[package]
name = "brain-test-data"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"

nalgebra = "0.18.0"

rlbot = "0.4.1"

collect = { path = "../collect" }

[build-dependencies]
csv = "1.0.2"

[features]
strict = []
